language: ruby
script: bundle install; bundle exec rake test

rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - 1.9.2
gemfile:
  - gemfiles/Gemfile-rails.3.2.0
  - gemfiles/Gemfile-rails.3.2.x

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile-rails.3.2.0
